// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANexwbRWKnFck0ww7gauAg4ViZWxVm3ig',
    appId: '1:964411139557:web:f82d6e734caeb13001bb0c',
    messagingSenderId: '964411139557',
    projectId: 'myneo-abe0b',
    authDomain: 'myneo-abe0b.firebaseapp.com',
    storageBucket: 'myneo-abe0b.appspot.com',
    measurementId: 'G-T3TP7JTK7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdeyOV1SAGp5xYCI7Dgv-A01KJ6VpKGbM',
    appId: '1:964411139557:android:ec6e78d8dd2d3d7501bb0c',
    messagingSenderId: '964411139557',
    projectId: 'myneo-abe0b',
    storageBucket: 'myneo-abe0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2KzI1vwC4GA0v9tYSYUkroGfCzw1leHU',
    appId: '1:964411139557:ios:9566e14883c477ca01bb0c',
    messagingSenderId: '964411139557',
    projectId: 'myneo-abe0b',
    storageBucket: 'myneo-abe0b.appspot.com',
    iosClientId: '964411139557-mqi162vp3vrkjcibb0vvhcmbotujjumk.apps.googleusercontent.com',
    iosBundleId: 'com.example.myneo.myNeo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2KzI1vwC4GA0v9tYSYUkroGfCzw1leHU',
    appId: '1:964411139557:ios:9566e14883c477ca01bb0c',
    messagingSenderId: '964411139557',
    projectId: 'myneo-abe0b',
    storageBucket: 'myneo-abe0b.appspot.com',
    iosClientId: '964411139557-mqi162vp3vrkjcibb0vvhcmbotujjumk.apps.googleusercontent.com',
    iosBundleId: 'com.example.myneo.myNeo',
  );
}
